language: clojure
install:
  - curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > my-lein
  - chmod +x my-lein
  - ./my-lein deps
  - ./my-lein --version
script: ./my-lein test-all
jdk:
- oraclejdk8
